import React from "react";
import { LineSet } from "./LineSet";

export const MockInterface = ({ id_prefix }: { id_prefix: string }) => {
  return (
    <>
      <rect
        id={`background-${id_prefix}`}
        width="200px"
        height="300px"
        fill="#0c121e"
        color="#0c121e"
        stroke="#0c121e"
        strokeWidth={1}
      />
      <line
        id={`header-${id_prefix}`}
        stroke="white"
        strokeWidth={2}
        strokeDasharray="10 5"
        x1={100}
        x2={190}
        y1={8}
        y2={8}
      />
      <rect
        id={`sub_header-${id_prefix}`}
        y="15"
        width="200px"
        height="60px"
        fill="#323642"
        color="#323642"
        stroke="#323642"
        strokeWidth={1}
      />
      <g id={`sub_header_text-${id_prefix}`}>
        <LineSet
          isHorizontal={true}
          amount={3}
          distanceBetween={10}
          size={90}
          startX={5}
          startY={25}
          randomness={0.2}
        />
      </g>
      <rect
        id={`button-${id_prefix}`}
        y="55"
        x="10"
        width="40px"
        height="10px"
        fill="#4c53c8"
        color="#4c53c8"
        stroke="#4c53c8"
        strokeWidth={1}
      />
      <rect
        id={`article_1-${id_prefix}`}
        y="90"
        x="10"
        width="40px"
        height="50px"
        fill="#acd0ea"
        color="#acd0ea"
        stroke="#acd0ea"
        strokeWidth={1}
        rx={5}
      />
      <g id={`text_article_1-${id_prefix}`}>
        <LineSet
          isHorizontal={true}
          amount={3}
          distanceBetween={10}
          size={40}
          startX={60}
          startY={100}
          randomness={0.2}
        />
      </g>
      <rect
        id={`article_2-${id_prefix}`}
        y="90"
        x="110"
        width="40px"
        height="50px"
        fill="#edc5c5"
        color="#edc5c5"
        stroke="#edc5c5"
        strokeWidth={1}
        rx={5}
      />
      <rect
        id={`article_3-${id_prefix}`}
        y="90"
        x="155"
        width="40px"
        height="50px"
        fill="#dca09f"
        color="#dca09f"
        stroke="#dca09f"
        strokeWidth={1}
        rx={5}
      />
      <g id={`text_article_1_1-${id_prefix}`}>
        <LineSet
          isHorizontal={true}
          amount={3}
          distanceBetween={10}
          size={40}
          startX={10}
          startY={150}
          randomness={0.2}
        />
      </g>
      <g id={`text_article_2-${id_prefix}`}>
        <LineSet
          isHorizontal={true}
          amount={3}
          distanceBetween={10}
          size={30}
          startX={110}
          startY={150}
          randomness={0.2}
        />
      </g>
      <g id={`text_article_3-${id_prefix}`}>
        <LineSet
          isHorizontal={true}
          amount={3}
          distanceBetween={10}
          size={30}
          startX={160}
          startY={150}
          randomness={0.2}
        />
      </g>
      <rect
        id={`image-${id_prefix}`}
        y="200"
        x="10"
        width="150px"
        height="50px"
        fill="#941528"
        color="#941528"
        stroke="#941528"
        strokeWidth={1}
        rx={5}
      />
    </>
  );
};
